### ISSUE TITLE
编译失败问题

### ISSUE THREAD

**Issue by xiangxyq** [aliyun/alibabacloud-nls-cpp-sdk#6]
hi,
Ubuntu16.04下编译出现以下问题
![image](https://user-images.githubusercontent.com/18209169/130068220-e1f154be-9713-48a8-892e-af60e3ce1d5d.png)

**Comment by soildierKing** [comment]
很抱歉，已经离职，不在维护。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xiang XYQ ***@***.***&gt;
发送时间: 2021年8月19日 20:28
收件人: aliyun/alibabacloud-nls-cpp-sdk ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[aliyun/alibabacloud-nls-cpp-sdk] 编译失败问题 (#6)





 
hi,
 Ubuntu16.04下编译出现以下问题
 
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiangxyq** [comment]
已经找到问题的原因了，是因为编译生成的的libsoncpp.a的路径和cmake中设置的路径不一致了，临时解决可以改一下nlsCppSdk/linux.nlsCppSdk.cmake 
![image](https://user-images.githubusercontent.com/18209169/130166563-9e102464-b76a-4c22-b5e1-ab9a0a32e1a1.png)
